import {Dimensions, StyleSheet} from 'react-native';
import {SearchBar} from 'react-native-screens';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: 'black',
  },
  input: {
    width: '100%',
    padding: 15,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    marginBottom: 15,
    backgroundColor: '#fff',
  },
  button: {
    backgroundColor: '#000',
    borderRadius: 8,
    alignItems: 'center',
    home: {
      width: '70%',
      marginBottom: 10,
      padding: 20,
      marginTop: 10,
    },
    sigin: {
      width: '100%',
      padding: 15,
      marginTop: 10,
    },
    createAccount: {
      width: '100%',
      padding: 15,
      marginTop: 10,
    },
    submit: {
      padding: 10,
      justifyContent: 'center',
    },
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  linkText: {
    color: 'gray',
    fontSize: 15,
    textDecorationLine: 'underline',
  },
  bodyText: {
    color: '#000',
    marginTop: 15,
    fontSize: 16,
  },
  header: {
    backgroundColor: 'white',
    justifyContent: 'center',
    marginVertical: 30,
    width: Dimensions.get('window').width,
    paddingHorizontal: 10,
    marginTop: Dimensions.get('window').height * 0.1,
    main: {
      marginTop: Dimensions.get('window').height * 0.05,
    },
  },
  modalContainer: {
    alignItems: 'center',
    height: '90%',
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    borderWidth: 5,
    borderColor: '#000',
  },
  modalHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalCloseButton: {
    backgroundColor: '#000',
    borderRadius: 5,
  },
  modalBody: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  modalBodyRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  modalBodyColumn: {
    flexDirection: 'column',
    paddingVertical: 50,
  },
  inputText: {
    fontSize: 18,
    padding: 5,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    marginBottom: 10,
    date: {
      backgroundColor: '#f5f5f5',
      borderRadius: 0,
      borderWidth: 0,
    },
    time: {
      backgroundColor: '#f5f5f5',
      borderRadius: 8,
      borderWidth: 0,
      marginLeft: 10,
      paddingLeft: 10,
      paddingRight: 10,
      color: '#000',
      fontWeight: 'bold',
      fontSize: 12,
      width: 120,
      height: 35,
    },
    long: {},
  },
  datePickerModal: {
    alignItems: 'center',
    height: '50%',
    width: '90%',
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    padding: 20,
    borderWidth: 5,
    borderColor: '#000',
  },
  listItem: {
    paddingVertical: 20,
    borderBottomWidth: 3,
    borderBottomColor: '#000',
    width: Dimensions.get('screen').width * 0.9,
    backgroundColor: '#fff',
  },
  listItemModal: {
    width: Dimensions.get('screen').width * 0.65,
    backgroundColor: '#fff',
    paddingVertical: 20,
    borderBottomWidth: 3,
    borderBottomColor: '#000',
  },
  listItemText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    lineHeight: 25,
  },
  noDataText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 10,
  },
  backButton: {
    position: 'absolute',
    bottom: 20,
    padding: 10,
  },
  backButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  swipeButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 80,
    padding: 15,
  },
  editButton: {
    backgroundColor: '#3498db',
    width: 100,
    height: '100%',
  },
  deleteButton: {
    backgroundColor: '#e74c3c',
    width: 100,
    height: '100%',
  },
  swipeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  hiddenButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    flex: 1,
    borderRadius: 5,
  },
  searchBar: {
    width: Dimensions.get('screen').width * 0.9,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 30,
    padding: 10,
    borderColor: '#000',
  },
});

export default styles;
